### ISSUE TITLE
No. 33 on Walkthrough of the steps performed to get authentication working in Node

### ISSUE THREAD

**Issue by igaboc** [developingAlex/lakedisappointment#2]
- when reaching to line 33 on walk through of the api, testing failed. Changed the api/routes/auth.js file to comment out:
const User = require(‘../model/User’) and changing the register post to:
router.post('/auth/register',
  /* middleware that handles the registration process */
  authMiddleware.register,
  /* json handler */
  (req, res) => {
    res.json({
      user: req.user
    })
  }
)

**Comment by developingAlex** [comment]
Thanks for this! I've updated it now
